### ISSUE TITLE
搜狗输入法不能使用

### ISSUE THREAD

**Issue by yyancy** [A-23187/AIMSwitcher#1]
在搜狗输入法下, 中文模式`AIMSwitcher.exe --imm` 输出`1`; 英文模式输出`0`. 

英文模式下, 输入`AIMSwitcher.exe --imm 1`没有反应, 没有切换.

**Comment by isudfv** [comment]
https://github.com/hadix-lin/ideavim_extension/issues/70#issuecomment-1567879599

> 在搜狗输入法下, 中文模式`AIMSwitcher.exe --imm` 输出`1`; 英文模式输出`0`.
> 
> 英文模式下, 输入`AIMSwitcher.exe --imm 1`没有反应, 没有切换.

https://github.com/hadix-lin/ideavim_extension/issues/70#issuecomment-1567879599

**Comment by yyancy** [comment]
说一下吧， 我现在用[im-select](https://github.com/daipeihust/im-select)可以实现输入法的切换
